version: '3.8'

services:
  client:
    build:
      context: ./groupB/dashboard/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5106
    depends_on:
      - server-node
      - server-python

  server-node:
    build:
      context: ./groupB/dashboard/server
      dockerfile: Dockerfile
    ports:
      - "5105:5105"
    volumes:
      - ./groupB/dashboard/server/pioneer_key.json:/usr/src/app/pioneer_key.json
    env_file:
      - ./groupB/dashboard/server/.env

  server-python:
    build:
      context: ./python
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - "5106:5106"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=all
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    volumes:
      - ./python/storage:/app/storage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]